library(tree)
library(ISLR)
attach(OJ)
set.seed(2)
train = sample(1:nrow(OJ), 800)
OJ.test = OJ[-train,]
tree.OJ = tree(Purchase ~ ., data = OJ, subset = train)
summary(tree.OJ)
plot(tree.OJ)
text(tree.OJ, pretty = 0)
tree.pred = predict(tree.OJ, OJ.test, type = "class")
table(tree.pred, OJ.test$Purchase)
(148 + 70) / 270
set.seed(7)
cv.OJ = cv.tree(tree.OJ, FUN = prune.misclass)
cv.OJ
plot(cv.OJ$size, cv.OJ$dev, type = "b")
prune.OJ = prune.misclass(tree.OJ, best = 4)
plot(prune.OJ)
text(prune.OJ, pretty = 0)
tree.pred = predict(prune.OJ, OJ.test, type = "class")
table(tree.pred, OJ.test$Purchase)
prune.OJ = prune.misclass(tree.OJ, best = 5)
tree.pred = predict(prune.OJ, OJ.test, type = "class")
table(tree.pred, OJ.test$Purchase)
(148 + 70) / 270
attach(Carseats)
set.seed(2)
train = sample(1:nrow(Carseats), nrow(Carseats) / 2)
Carseats.test = Carseats[-train,]
tree.Carseats = tree(Sales ~ ., Carseats, subset = train)
summary(tree.Carseats)
yhat = predict(tree.Carseats, newdata = Carseats[-train,])
mean((yhat - Carseats.test$Sales) ^ 2)
cv.Carseats = cv.tree(tree.Carseats)
plot(cv.Carseats$size, cv.Carseats$dev, type = 'b')
cv.Carseats
prune.Carseats = prune.tree(tree.Carseats, best = 17)
yhat = predict(prune.Carseats, newdata = Carseats[-train,])
mean((yhat - Carseats.test$Sales) ^ 2)
library(randomForest)
set.seed(1)
bag.Carseats = randomForest(Sales ~ ., data = Carseats, subset = train, mtry = 10, importance = TRUE)
bag.Carseats
yhat.bag = predict(bag.Carseats, newdata = Carseats[-train,])
mean((yhat - Carseats.test$Sales) ^ 2)
set.seed(1)
rf.Carseats = randomForest(Sales ~ ., data = Carseats, subset = train, mtry = 10 / 3, importance = TRUE)
yhat.bag = predict(rf.Carseats, newdata = Carseats[-train,])
mean((yhat - Carseats.test$Sales) ^ 2)
importance(rf.Carseats)
varImpPlot(rf.Carseats)