Auto = read.csv("Auto.csv", header = T, na.strings = "?")
Auto = na.omit(Auto)
lm.fit = lm(mpg ~ weight, data = Auto)
summary(lm.fit)
attach(Auto)
predict(lm.fit, data.frame(weight = c(2000)), interval = "confidence")
predict(lm.fit, data.frame(weight = c(2000)), interval = "prediction")
plot(weight, mpg)
abline(lm.fit, col = "red")
par(mfrow = c(2, 2))
plot(lm.fit)
College = read.csv("College.csv", header = T, na.strings = "?")
graduation = lm(Grad.Rate ~ Private + Apps + Accept + Enroll + Top10perc +
                Top25perc + PhD + Terminal + S.F.Ratio + Expend, data = College)
summary(graduation)
summary(lm(Grad.Rate ~ Private * Top10perc, data = College))
summary(lm(Grad.Rate ~ Private + Top10perc + Private:Top10perc, data = College))
vif(graduation)
summary(lm(Grad.Rate ~ Private + Apps + Accept + Enroll +
           Top10perc + Top25perc + PhD + Terminal + S.F.Ratio, data = College))
summary(lm(Grad.Rate ~ Private + Apps + Accept + Enroll +
           Top10perc + Top25perc + PhD + Terminal, data = College))
summary(lm(Grad.Rate ~ Private + Apps + Accept + Enroll + Top10perc + Top25perc + PhD, data = College))
summary(lm(Grad.Rate ~ Private + Apps + Enroll + Top10perc + Top25perc + PhD, data = College))
summary(lm(Grad.Rate ~ Private + Apps + Enroll + Top25perc + PhD, data = College))